# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  which-project:  # id of input
    description: 'Which sample project to build'
    required: true
    default: 'cc26xx-web-demo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.which-project }}
